CREATE TABLE agent_arxiv_tool_log
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id           VARCHAR(64)              NOT NULL,
    request_user_id      BIGINT,
    request_username     VARCHAR(64),
    query                VARCHAR(1024)            NOT NULL,
    max_results          INTEGER                  NOT NULL DEFAULT 0,
    include_full_text    BOOLEAN                  NOT NULL DEFAULT FALSE,
    result_count         INTEGER                  NOT NULL DEFAULT 0,
    knowledge_base_id    BIGINT,
    entry_id             VARCHAR(256),
    title                VARCHAR(512),
    pdf_url              VARCHAR(512),
    status               VARCHAR(32)              NOT NULL,
    document_id          BIGINT,
    rag_ingestion_job_id BIGINT,
    error_message        VARCHAR(1024),
    started_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at          TIMESTAMP WITH TIME ZONE,
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_arxiv_log_kb FOREIGN KEY (knowledge_base_id) REFERENCES rag_knowledge_base (id),
    CONSTRAINT fk_arxiv_log_doc FOREIGN KEY (document_id) REFERENCES rag_user_document (id),
    CONSTRAINT fk_arxiv_log_rag_job FOREIGN KEY (rag_ingestion_job_id) REFERENCES rag_ingestion_job (id)
);

CREATE INDEX idx_arxiv_log_request ON agent_arxiv_tool_log (request_id);
CREATE INDEX idx_arxiv_log_user_created ON agent_arxiv_tool_log (request_user_id, created_at);
CREATE INDEX idx_arxiv_log_kb_entry_status ON agent_arxiv_tool_log (knowledge_base_id, entry_id, status);
CREATE INDEX idx_arxiv_log_status ON agent_arxiv_tool_log (status);
