ALTER TABLE rag_knowledge_base ADD COLUMN default_search_mode VARCHAR(20) NOT NULL DEFAULT 'HYBRID';
ALTER TABLE rag_knowledge_base ADD COLUMN rerank_enabled BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE rag_knowledge_base ADD COLUMN vector_weight DECIMAL(5, 4) NOT NULL DEFAULT 0.6500;
ALTER TABLE rag_knowledge_base ADD COLUMN keyword_weight DECIMAL(5, 4) NOT NULL DEFAULT 0.3500;
ALTER TABLE rag_knowledge_base ADD COLUMN candidate_top_k INTEGER NOT NULL DEFAULT 50;
ALTER TABLE rag_knowledge_base ADD COLUMN context_top_k INTEGER NOT NULL DEFAULT 6;
ALTER TABLE rag_knowledge_base ADD COLUMN chunk_size INTEGER NOT NULL DEFAULT 800;
ALTER TABLE rag_knowledge_base ADD COLUMN chunk_overlap INTEGER NOT NULL DEFAULT 120;

ALTER TABLE rag_user_document ADD COLUMN source_uri VARCHAR(1024);
ALTER TABLE rag_user_document ADD COLUMN parser_type VARCHAR(64);
ALTER TABLE rag_user_document ADD COLUMN chunk_strategy VARCHAR(64);
ALTER TABLE rag_user_document ADD COLUMN embedding_model VARCHAR(128);
ALTER TABLE rag_user_document ADD COLUMN embedding_dimension INTEGER;
ALTER TABLE rag_user_document ADD COLUMN indexed_at TIMESTAMP WITH TIME ZONE;

ALTER TABLE rag_document_chunk ADD COLUMN content_hash VARCHAR(64);
ALTER TABLE rag_document_chunk ADD COLUMN heading_path VARCHAR(512);
ALTER TABLE rag_document_chunk ADD COLUMN start_offset INTEGER;
ALTER TABLE rag_document_chunk ADD COLUMN end_offset INTEGER;
ALTER TABLE rag_document_chunk ADD COLUMN metadata_jsonb TEXT;
ALTER TABLE rag_document_chunk ADD COLUMN search_vector TEXT;

CREATE INDEX idx_rag_chunk_content_hash ON rag_document_chunk (content_hash);

CREATE TABLE rag_retrieval_trace
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id              VARCHAR(64)              NOT NULL,
    user_id               BIGINT,
    query_text            TEXT                     NOT NULL,
    knowledge_base_ids    VARCHAR(1024),
    search_mode           VARCHAR(20)              NOT NULL,
    rerank_enabled        BOOLEAN                  NOT NULL DEFAULT FALSE,
    degraded              BOOLEAN                  NOT NULL DEFAULT FALSE,
    degrade_reason        VARCHAR(1024),
    result_count          INTEGER                  NOT NULL DEFAULT 0,
    cost_ms               BIGINT                   NOT NULL DEFAULT 0,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by            BIGINT,
    updated_by            BIGINT,
    version               BIGINT                   NOT NULL DEFAULT 0,
    deleted               BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_rag_trace_id_deleted UNIQUE (trace_id, deleted)
);

CREATE INDEX idx_rag_trace_user_created ON rag_retrieval_trace (user_id, created_at);

CREATE TABLE rag_retrieval_trace_item
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id          VARCHAR(64)              NOT NULL,
    stage             VARCHAR(20)              NOT NULL,
    rank_no           INTEGER                  NOT NULL,
    knowledge_base_id BIGINT,
    document_id       BIGINT,
    chunk_id          BIGINT,
    chunk_index       INTEGER,
    score             DOUBLE PRECISION,
    vector_score      DOUBLE PRECISION,
    keyword_score     DOUBLE PRECISION,
    fusion_score      DOUBLE PRECISION,
    rerank_score      DOUBLE PRECISION,
    matched_by        VARCHAR(64),
    content_preview   VARCHAR(512),
    metadata_json     TEXT,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        BIGINT,
    updated_by        BIGINT,
    version           BIGINT                   NOT NULL DEFAULT 0,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_rag_trace_item_trace_stage ON rag_retrieval_trace_item (trace_id, stage, rank_no);

CREATE TABLE rag_feedback
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id          VARCHAR(64),
    message_id        VARCHAR(64),
    user_id           BIGINT,
    feedback_type     VARCHAR(32)              NOT NULL,
    question          TEXT,
    answer_preview    VARCHAR(1024),
    source_chunk_ids  VARCHAR(1024),
    comment_text      VARCHAR(1024),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        BIGINT,
    updated_by        BIGINT,
    version           BIGINT                   NOT NULL DEFAULT 0,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_rag_feedback_trace ON rag_feedback (trace_id);
CREATE INDEX idx_rag_feedback_user_created ON rag_feedback (user_id, created_at);
