CREATE TABLE agent_chat_preset
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name               VARCHAR(128)             NOT NULL,
    description        VARCHAR(512),
    model_config_json  TEXT,
    model_options_json TEXT,
    system_prompt      TEXT                     NOT NULL,
    tool_config_json   TEXT,
    agent_options_json TEXT,
    enabled            BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by         BIGINT,
    updated_by         BIGINT,
    version            BIGINT                   NOT NULL DEFAULT 0,
    deleted            BOOLEAN                  NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_agent_chat_preset_enabled_deleted ON agent_chat_preset (enabled, deleted);
CREATE INDEX idx_agent_chat_preset_name ON agent_chat_preset (name);
CREATE INDEX idx_agent_chat_preset_created_by ON agent_chat_preset (created_by);

CREATE TABLE agent_conversation_audit
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id            VARCHAR(64),
    trace_id              VARCHAR(64),
    user_id               BIGINT,
    username              VARCHAR(128),
    thread_id             VARCHAR(128)             NOT NULL,
    preset_id             BIGINT,
    runtime_fingerprint   VARCHAR(128),
    effective_config_json TEXT,
    status                VARCHAR(32)              NOT NULL,
    started_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at           TIMESTAMP WITH TIME ZONE,
    duration_ms           BIGINT,
    error_code            VARCHAR(256),
    error_message         VARCHAR(1024),
    ip                    VARCHAR(64),
    user_agent            VARCHAR(512),
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_agent_conversation_audit_user_created ON agent_conversation_audit (user_id, created_at);
CREATE INDEX idx_agent_conversation_audit_thread ON agent_conversation_audit (thread_id);
CREATE INDEX idx_agent_conversation_audit_trace ON agent_conversation_audit (trace_id);
CREATE INDEX idx_agent_conversation_audit_status ON agent_conversation_audit (status);

CREATE TABLE agent_conversation_message_audit
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_audit_id BIGINT                   NOT NULL,
    seq_no                INTEGER                  NOT NULL,
    role                  VARCHAR(32)              NOT NULL,
    message_type          VARCHAR(32)              NOT NULL,
    content               TEXT,
    content_chars         INTEGER,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_agent_conversation_message_audit_conversation
    ON agent_conversation_message_audit (conversation_audit_id, seq_no);
