CREATE TABLE agent_run_audit
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id            VARCHAR(64),
    trace_id              VARCHAR(64),
    thread_id             VARCHAR(128)             NOT NULL,
    user_id               BIGINT,
    username              VARCHAR(128),
    preset_id             BIGINT,
    runtime_fingerprint   VARCHAR(128),
    effective_config_json TEXT,
    user_message          TEXT,
    final_message         TEXT,
    final_thinking        TEXT,
    status                VARCHAR(32)              NOT NULL,
    model_call_count      INTEGER                  NOT NULL DEFAULT 0,
    tool_call_count       INTEGER                  NOT NULL DEFAULT 0,
    mcp_tool_call_count   INTEGER                  NOT NULL DEFAULT 0,
    started_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at           TIMESTAMP WITH TIME ZONE,
    duration_ms           BIGINT,
    error_code            VARCHAR(256),
    error_message         TEXT,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_agent_run_audit_user_created ON agent_run_audit (user_id, created_at);
CREATE INDEX idx_agent_run_audit_thread ON agent_run_audit (thread_id);
CREATE INDEX idx_agent_run_audit_trace ON agent_run_audit (trace_id);
CREATE INDEX idx_agent_run_audit_request ON agent_run_audit (request_id);
CREATE INDEX idx_agent_run_audit_status_created ON agent_run_audit (status, created_at);

CREATE TABLE agent_run_event_audit
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                BIGINT                   NOT NULL,
    request_id            VARCHAR(64),
    trace_id              VARCHAR(64),
    thread_id             VARCHAR(128),
    seq_no                INTEGER                  NOT NULL,
    event_type            VARCHAR(32)              NOT NULL,
    react_round           INTEGER,
    tool_call_id          VARCHAR(128),
    tool_name             VARCHAR(192),
    tool_type             VARCHAR(32),
    mcp_server_code       VARCHAR(64),
    status                VARCHAR(32)              NOT NULL,
    started_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at           TIMESTAMP WITH TIME ZONE,
    duration_ms           BIGINT,
    model_provider        VARCHAR(32),
    model_name            VARCHAR(128),
    prompt_text           TEXT,
    request_messages_json TEXT,
    request_options_json  TEXT,
    available_tools_json  TEXT,
    response_text         TEXT,
    tool_arguments        TEXT,
    tool_result           TEXT,
    metadata_json         TEXT,
    error_code            VARCHAR(256),
    error_message         TEXT,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_agent_run_event_run FOREIGN KEY (run_id) REFERENCES agent_run_audit (id)
);

CREATE INDEX idx_agent_run_event_run_seq ON agent_run_event_audit (run_id, seq_no);
CREATE INDEX idx_agent_run_event_trace ON agent_run_event_audit (trace_id);
CREATE INDEX idx_agent_run_event_tool_created ON agent_run_event_audit (tool_name, created_at);
