CREATE TABLE agent_memory_session
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id                   VARCHAR(128)             NOT NULL,
    entry_type                   VARCHAR(32)              NOT NULL,
    title                        VARCHAR(256),
    user_id                      BIGINT                   NOT NULL,
    username                     VARCHAR(128),
    status                       VARCHAR(32)              NOT NULL,
    memory_enabled               BOOLEAN                  NOT NULL DEFAULT TRUE,
    long_term_extraction_enabled BOOLEAN                  NOT NULL DEFAULT TRUE,
    short_term_window_turns      INTEGER                  NOT NULL DEFAULT 10,
    last_active_at               TIMESTAMP WITH TIME ZONE,
    released_at                  TIMESTAMP WITH TIME ZONE,
    archived_at                  TIMESTAMP WITH TIME ZONE,
    deleted_at                   TIMESTAMP WITH TIME ZONE,
    created_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
    version                      BIGINT                   NOT NULL DEFAULT 0,
    deleted                      BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_agent_memory_session_id UNIQUE (session_id)
);

CREATE INDEX idx_agent_memory_session_user_status ON agent_memory_session (user_id, status, updated_at);
CREATE INDEX idx_agent_memory_session_entry_user ON agent_memory_session (entry_type, user_id, updated_at);
CREATE INDEX idx_agent_memory_session_deleted ON agent_memory_session (deleted);

CREATE TABLE agent_memory_message
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       VARCHAR(128)             NOT NULL,
    user_id          BIGINT                   NOT NULL,
    entry_type       VARCHAR(32)              NOT NULL,
    seq_no           INTEGER                  NOT NULL,
    turn_no          INTEGER                  NOT NULL,
    role             VARCHAR(32)              NOT NULL,
    message_type     VARCHAR(32)              NOT NULL,
    content          TEXT,
    content_chars    INTEGER,
    source_refs_json TEXT,
    trace_id         VARCHAR(64),
    request_id       VARCHAR(64),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    deleted          BOOLEAN                  NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_agent_memory_message_session_seq ON agent_memory_message (session_id, seq_no);
CREATE INDEX idx_agent_memory_message_user_created ON agent_memory_message (user_id, created_at);
CREATE INDEX idx_agent_memory_message_entry_created ON agent_memory_message (entry_type, created_at);
CREATE INDEX idx_agent_memory_message_deleted ON agent_memory_message (deleted);

CREATE TABLE agent_long_term_memory
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT                   NOT NULL,
    username          VARCHAR(128),
    scope_type        VARCHAR(32)              NOT NULL,
    content_markdown  TEXT                     NOT NULL,
    content_chars     INTEGER                  NOT NULL,
    active_version_id BIGINT,
    status            VARCHAR(32)              NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    version           BIGINT                   NOT NULL DEFAULT 0,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX idx_agent_long_term_memory_user_scope
    ON agent_long_term_memory (user_id, scope_type)
    WHERE deleted = FALSE;
CREATE INDEX idx_agent_long_term_memory_status ON agent_long_term_memory (status);

CREATE TABLE agent_long_term_memory_version
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    memory_id          BIGINT                   NOT NULL,
    version_no         INTEGER                  NOT NULL,
    content_markdown   TEXT                     NOT NULL,
    content_chars      INTEGER                  NOT NULL,
    change_summary     TEXT,
    source_session_ids TEXT,
    source_message_ids TEXT,
    request_id         VARCHAR(64),
    trace_id           VARCHAR(64),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_agent_long_term_memory_version_memory ON agent_long_term_memory_version (memory_id, version_no);

CREATE TABLE agent_memory_extraction_audit
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT                   NOT NULL,
    session_id         VARCHAR(128),
    entry_type         VARCHAR(32),
    source_message_ids TEXT,
    status             VARCHAR(32)              NOT NULL,
    extracted_markdown TEXT,
    merged_version_id  BIGINT,
    error_code         VARCHAR(256),
    error_message      TEXT,
    request_id         VARCHAR(64),
    trace_id           VARCHAR(64),
    started_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at        TIMESTAMP WITH TIME ZONE,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_agent_memory_extraction_user_created ON agent_memory_extraction_audit (user_id, created_at);
CREATE INDEX idx_agent_memory_extraction_session ON agent_memory_extraction_audit (session_id);
CREATE INDEX idx_agent_memory_extraction_status ON agent_memory_extraction_audit (status);
