CREATE TABLE sys_user
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username         VARCHAR(64)              NOT NULL,
    nickname         VARCHAR(64),
    password_hash    VARCHAR(128)             NOT NULL,
    email            VARCHAR(128),
    mobile           VARCHAR(32),
    avatar_url       VARCHAR(512),
    status           VARCHAR(20)              NOT NULL DEFAULT 'ENABLED',
    locked           BOOLEAN                  NOT NULL DEFAULT FALSE,
    password_expired BOOLEAN                  NOT NULL DEFAULT FALSE,
    last_login_at    TIMESTAMP WITH TIME ZONE,
    remark           VARCHAR(255),
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by       BIGINT,
    updated_by       BIGINT,
    version          BIGINT                   NOT NULL DEFAULT 0,
    deleted          BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_user_username_deleted UNIQUE (username, deleted),
    CONSTRAINT uk_user_email_deleted UNIQUE (email, deleted),
    CONSTRAINT uk_user_mobile_deleted UNIQUE (mobile, deleted)
);

CREATE INDEX idx_user_status ON sys_user (status);
CREATE INDEX idx_user_deleted ON sys_user (deleted);

CREATE TABLE sys_role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code   VARCHAR(64)              NOT NULL,
    role_name   VARCHAR(64)              NOT NULL,
    status      VARCHAR(20)              NOT NULL DEFAULT 'ENABLED',
    sort_no     INTEGER                  NOT NULL DEFAULT 0,
    built_in    BOOLEAN                  NOT NULL DEFAULT FALSE,
    description VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by  BIGINT,
    updated_by  BIGINT,
    version     BIGINT                   NOT NULL DEFAULT 0,
    deleted     BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_role_code_deleted UNIQUE (role_code, deleted)
);

CREATE INDEX idx_role_status ON sys_role (status);
CREATE INDEX idx_role_deleted ON sys_role (deleted);

CREATE TABLE sys_permission
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perm_code   VARCHAR(128)             NOT NULL,
    perm_name   VARCHAR(128)             NOT NULL,
    perm_type   VARCHAR(20)              NOT NULL,
    parent_id   BIGINT,
    status      VARCHAR(20)              NOT NULL DEFAULT 'ENABLED',
    sort_no     INTEGER                  NOT NULL DEFAULT 0,
    description VARCHAR(255),
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by  BIGINT,
    updated_by  BIGINT,
    version     BIGINT                   NOT NULL DEFAULT 0,
    deleted     BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_permission_code_deleted UNIQUE (perm_code, deleted),
    CONSTRAINT fk_permission_parent FOREIGN KEY (parent_id) REFERENCES sys_permission (id)
);

CREATE INDEX idx_permission_type ON sys_permission (perm_type);
CREATE INDEX idx_permission_parent ON sys_permission (parent_id);
CREATE INDEX idx_permission_status ON sys_permission (status);
CREATE INDEX idx_permission_deleted ON sys_permission (deleted);

CREATE TABLE sys_menu
(
    permission_id  BIGINT PRIMARY KEY,
    parent_menu_id BIGINT,
    route_name     VARCHAR(128),
    route_path     VARCHAR(255),
    component      VARCHAR(255),
    redirect       VARCHAR(255),
    icon           VARCHAR(128),
    hidden         BOOLEAN NOT NULL DEFAULT FALSE,
    cacheable      BOOLEAN NOT NULL DEFAULT TRUE,
    external_link  VARCHAR(512),
    CONSTRAINT uk_menu_route_name UNIQUE (route_name),
    CONSTRAINT fk_menu_permission FOREIGN KEY (permission_id) REFERENCES sys_permission (id),
    CONSTRAINT fk_menu_parent FOREIGN KEY (parent_menu_id) REFERENCES sys_permission (id)
);

CREATE INDEX idx_menu_parent ON sys_menu (parent_menu_id);

CREATE TABLE sys_button
(
    permission_id      BIGINT PRIMARY KEY,
    menu_permission_id BIGINT      NOT NULL,
    button_key         VARCHAR(64) NOT NULL,
    frontend_action    VARCHAR(128),
    style_hint         VARCHAR(64),
    description        VARCHAR(255),
    CONSTRAINT uk_button_menu_key UNIQUE (menu_permission_id, button_key),
    CONSTRAINT fk_button_permission FOREIGN KEY (permission_id) REFERENCES sys_permission (id),
    CONSTRAINT fk_button_menu FOREIGN KEY (menu_permission_id) REFERENCES sys_permission (id)
);

CREATE INDEX idx_button_menu ON sys_button (menu_permission_id);

CREATE TABLE sys_api
(
    permission_id   BIGINT PRIMARY KEY,
    http_method     VARCHAR(16)  NOT NULL,
    url_pattern     VARCHAR(512) NOT NULL,
    matcher_type    VARCHAR(20)  NOT NULL,
    public_flag     BOOLEAN      NOT NULL DEFAULT FALSE,
    service_tag     VARCHAR(128),
    operation_name  VARCHAR(128),
    risk_level      VARCHAR(20)  NOT NULL DEFAULT 'LOW',
    last_scanned_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_api_method_pattern_type UNIQUE (http_method, url_pattern, matcher_type),
    CONSTRAINT fk_api_permission FOREIGN KEY (permission_id) REFERENCES sys_permission (id)
);

CREATE INDEX idx_api_public ON sys_api (public_flag);

CREATE TABLE sys_user_role
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL,
    role_id    BIGINT                   NOT NULL,
    granted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    granted_by BIGINT,
    CONSTRAINT uk_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES sys_role (id)
);

CREATE INDEX idx_user_role_user ON sys_user_role (user_id);
CREATE INDEX idx_user_role_role ON sys_user_role (role_id);

CREATE TABLE sys_role_inheritance
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id           BIGINT                   NOT NULL,
    inherited_role_id BIGINT                   NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        BIGINT,
    CONSTRAINT uk_role_inheritance UNIQUE (role_id, inherited_role_id),
    CONSTRAINT ck_role_inherit_not_self CHECK (role_id <> inherited_role_id),
    CONSTRAINT fk_role_inherit_role FOREIGN KEY (role_id) REFERENCES sys_role (id),
    CONSTRAINT fk_role_inherit_inherited FOREIGN KEY (inherited_role_id) REFERENCES sys_role (id)
);

CREATE INDEX idx_role_inherit_role ON sys_role_inheritance (role_id);
CREATE INDEX idx_role_inherit_target ON sys_role_inheritance (inherited_role_id);

CREATE TABLE sys_role_permission
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id       BIGINT                   NOT NULL,
    permission_id BIGINT                   NOT NULL,
    granted_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    granted_by    BIGINT,
    CONSTRAINT uk_role_permission UNIQUE (role_id, permission_id),
    CONSTRAINT fk_role_permission_role FOREIGN KEY (role_id) REFERENCES sys_role (id),
    CONSTRAINT fk_role_permission_permission FOREIGN KEY (permission_id) REFERENCES sys_permission (id)
);

CREATE INDEX idx_role_permission_role ON sys_role_permission (role_id);
CREATE INDEX idx_role_permission_permission ON sys_role_permission (permission_id);

CREATE TABLE sys_button_api
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    button_permission_id BIGINT                   NOT NULL,
    api_permission_id    BIGINT                   NOT NULL,
    relation_type        VARCHAR(32)              NOT NULL DEFAULT 'CALLS',
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by           BIGINT,
    CONSTRAINT uk_button_api UNIQUE (button_permission_id, api_permission_id),
    CONSTRAINT fk_button_api_button FOREIGN KEY (button_permission_id) REFERENCES sys_permission (id),
    CONSTRAINT fk_button_api_api FOREIGN KEY (api_permission_id) REFERENCES sys_permission (id)
);

CREATE INDEX idx_button_api_button ON sys_button_api (button_permission_id);
CREATE INDEX idx_button_api_api ON sys_button_api (api_permission_id);

CREATE TABLE sys_refresh_token
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id              BIGINT                   NOT NULL,
    token_id             VARCHAR(64)              NOT NULL,
    token_hash           VARCHAR(128)             NOT NULL,
    expires_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    revoked_at           TIMESTAMP WITH TIME ZONE,
    replaced_by_token_id VARCHAR(64),
    ip                   VARCHAR(64),
    user_agent           VARCHAR(512),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_refresh_token_id UNIQUE (token_id),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (user_id) REFERENCES sys_user (id)
);

CREATE INDEX idx_refresh_token_user ON sys_refresh_token (user_id);
CREATE INDEX idx_refresh_token_expires ON sys_refresh_token (expires_at);

CREATE TABLE sys_audit_log
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_user_id BIGINT,
    action        VARCHAR(128)             NOT NULL,
    target_type   VARCHAR(64),
    target_id     BIGINT,
    before_json   TEXT,
    after_json    TEXT,
    ip            VARCHAR(64),
    user_agent    VARCHAR(512),
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_actor_time ON sys_audit_log (actor_user_id, created_at);
CREATE INDEX idx_audit_action ON sys_audit_log (action);
CREATE INDEX idx_audit_target ON sys_audit_log (target_type, target_id);
