ALTER TABLE sys_user ADD COLUMN soul_md TEXT;
ALTER TABLE sys_user ADD COLUMN soul_md_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE sys_user ADD COLUMN soul_md_chars INTEGER NOT NULL DEFAULT 0;
ALTER TABLE sys_user ADD COLUMN soul_md_version_no INTEGER NOT NULL DEFAULT 1;
ALTER TABLE sys_user ADD COLUMN soul_md_updated_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE agent_soul_md_version
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT                   NOT NULL,
    username           VARCHAR(128),
    version_no         INTEGER                  NOT NULL,
    content_markdown   TEXT                     NOT NULL,
    content_chars      INTEGER                  NOT NULL,
    change_type        VARCHAR(32)              NOT NULL,
    change_summary     TEXT,
    source_type        VARCHAR(32),
    source_session_id  VARCHAR(128),
    source_message_ids TEXT,
    model_provider     VARCHAR(64),
    model_name         VARCHAR(128),
    request_id         VARCHAR(64),
    trace_id           VARCHAR(64),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_agent_soul_md_version_user_version ON agent_soul_md_version (user_id, version_no DESC);
CREATE INDEX idx_agent_soul_md_version_user_created ON agent_soul_md_version (user_id, created_at DESC);
