CREATE TABLE clocktower_game_public_mic_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    day_no INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL,
    current_holder_game_seat_id BIGINT,
    current_turn_id BIGINT,
    round_started_at TIMESTAMP WITH TIME ZONE,
    round_finished_at TIMESTAMP WITH TIME ZONE,
    grab_started_at TIMESTAMP WITH TIME ZONE,
    grab_ends_at TIMESTAMP WITH TIME ZONE,
    closed_at TIMESTAMP WITH TIME ZONE,
    metadata_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_clocktower_public_mic_session_game_day_deleted UNIQUE (game_id, day_no, deleted)
);

CREATE INDEX idx_clocktower_public_mic_session_game_status
    ON clocktower_game_public_mic_session (game_id, status);

CREATE TABLE clocktower_game_public_mic_turn (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    game_id BIGINT NOT NULL,
    day_no INTEGER NOT NULL,
    game_seat_id BIGINT NOT NULL,
    turn_order INTEGER NOT NULL,
    stage VARCHAR(32) NOT NULL,
    acquisition_type VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    ended_at TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    speech_event_id BIGINT,
    metadata_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_clocktower_public_mic_turn_session_order
    ON clocktower_game_public_mic_turn (session_id, turn_order);
CREATE INDEX idx_clocktower_public_mic_turn_game_seat
    ON clocktower_game_public_mic_turn (game_id, game_seat_id);
CREATE INDEX idx_clocktower_public_mic_turn_session_status
    ON clocktower_game_public_mic_turn (session_id, status);
