CREATE TABLE clocktower_game_nomination (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    open_game_id BIGINT,
    day_no INTEGER NOT NULL,
    nominator_game_seat_id BIGINT NOT NULL,
    nominee_game_seat_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    vote_count INTEGER NOT NULL DEFAULT 0,
    required_votes INTEGER NOT NULL DEFAULT 0,
    opened_at TIMESTAMP WITH TIME ZONE NOT NULL,
    closed_at TIMESTAMP WITH TIME ZONE,
    metadata_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_clocktower_game_nomination_game_day
    ON clocktower_game_nomination (game_id, day_no);
CREATE INDEX idx_clocktower_game_nomination_nominator_day
    ON clocktower_game_nomination (game_id, day_no, nominator_game_seat_id);
CREATE INDEX idx_clocktower_game_nomination_nominee_day
    ON clocktower_game_nomination (game_id, day_no, nominee_game_seat_id);
CREATE UNIQUE INDEX uk_clocktower_game_nomination_open
    ON clocktower_game_nomination (open_game_id, deleted);

CREATE TABLE clocktower_game_vote (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    nomination_id BIGINT NOT NULL,
    voter_game_seat_id BIGINT NOT NULL,
    vote_value BOOLEAN NOT NULL,
    used_dead_vote BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(32) NOT NULL,
    metadata_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX uk_clocktower_game_vote_nomination_voter
    ON clocktower_game_vote (nomination_id, voter_game_seat_id, deleted);
CREATE INDEX idx_clocktower_game_vote_game_nomination
    ON clocktower_game_vote (game_id, nomination_id);

CREATE TABLE clocktower_game_execution (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    day_no INTEGER NOT NULL,
    nominee_game_seat_id BIGINT,
    nomination_id BIGINT,
    status VARCHAR(32) NOT NULL,
    executed BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_at TIMESTAMP WITH TIME ZONE,
    metadata_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX uk_clocktower_game_execution_game_day
    ON clocktower_game_execution (game_id, day_no, deleted);
CREATE INDEX idx_clocktower_game_execution_game_status
    ON clocktower_game_execution (game_id, status);
