CREATE TABLE clocktower_game_night_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    night_no INTEGER NOT NULL,
    task_key VARCHAR(128) NOT NULL,
    actor_game_seat_id BIGINT,
    role_code VARCHAR(64),
    status VARCHAR(32) NOT NULL,
    mandatory BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    completed_at TIMESTAMP WITH TIME ZONE,
    skipped_at TIMESTAMP WITH TIME ZONE,
    metadata_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_clocktower_game_night_task_game_night
    ON clocktower_game_night_task (game_id, night_no);
CREATE INDEX idx_clocktower_game_night_task_game_status
    ON clocktower_game_night_task (game_id, status);
CREATE UNIQUE INDEX uk_clocktower_game_night_task_key
    ON clocktower_game_night_task (game_id, night_no, task_key, deleted);
