CREATE TABLE clocktower_agent_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    agent_instance_id BIGINT NOT NULL,
    game_seat_id BIGINT NOT NULL,
    trigger_type VARCHAR(64) NOT NULL,
    trigger_key VARCHAR(160) NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    priority INTEGER NOT NULL DEFAULT 100,
    available_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    locked_at TIMESTAMP WITH TIME ZONE,
    locked_by VARCHAR(128),
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}',
    result_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE UNIQUE INDEX uk_clocktower_agent_task_trigger
    ON clocktower_agent_task (game_id, agent_instance_id, trigger_type, trigger_key, deleted);

CREATE INDEX idx_clocktower_agent_task_pending
    ON clocktower_agent_task (status, available_at, priority, id);

CREATE INDEX idx_clocktower_agent_task_game_trigger
    ON clocktower_agent_task (game_id, trigger_type, status);
