CREATE TABLE clocktower_agent_memory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    agent_instance_id BIGINT NOT NULL,
    game_seat_id BIGINT NOT NULL,
    source_event_id BIGINT,
    source_event_seq BIGINT,
    memory_type VARCHAR(64) NOT NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'SELF',
    subject_game_seat_id BIGINT,
    subject_game_seat_id_key BIGINT NOT NULL DEFAULT -1,
    content_json JSONB NOT NULL DEFAULT '{}',
    confidence INTEGER NOT NULL DEFAULT 50,
    day_no INTEGER NOT NULL DEFAULT 0,
    night_no INTEGER NOT NULL DEFAULT 0,
    metadata_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_clocktower_agent_memory_subject_key
        CHECK (subject_game_seat_id_key = COALESCE(subject_game_seat_id, -1))
);

CREATE INDEX idx_clocktower_agent_memory_agent
    ON clocktower_agent_memory (game_id, agent_instance_id, created_at, deleted);

CREATE INDEX idx_clocktower_agent_memory_subject
    ON clocktower_agent_memory (game_id, subject_game_seat_id, deleted);

CREATE UNIQUE INDEX uk_clocktower_agent_memory_event
    ON clocktower_agent_memory (
        game_id,
        agent_instance_id,
        source_event_id,
        memory_type,
        subject_game_seat_id_key,
        deleted
    );
