CREATE TABLE clocktower_agent_decision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    agent_instance_id BIGINT NOT NULL,
    game_seat_id BIGINT NOT NULL,
    trigger_task_id BIGINT,
    phase VARCHAR(32) NOT NULL,
    day_no INTEGER NOT NULL DEFAULT 0,
    night_no INTEGER NOT NULL DEFAULT 0,
    decision_type VARCHAR(64) NOT NULL,
    policy_type VARCHAR(32) NOT NULL,
    legal_intents_json JSONB NOT NULL DEFAULT '[]',
    selected_intent_json JSONB NOT NULL DEFAULT '{}',
    reasoning_summary TEXT,
    model_provider VARCHAR(64),
    model_name VARCHAR(128),
    prompt_hash VARCHAR(128),
    status VARCHAR(32) NOT NULL DEFAULT 'ACCEPTED',
    error_message TEXT,
    metadata_json JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_by BIGINT,
    version BIGINT NOT NULL DEFAULT 0,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_clocktower_agent_decision_agent
    ON clocktower_agent_decision (game_id, agent_instance_id, created_at, deleted);

CREATE INDEX idx_clocktower_agent_decision_task
    ON clocktower_agent_decision (trigger_task_id, deleted);
