CREATE TABLE rag_knowledge_base
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                         VARCHAR(64)              NOT NULL,
    name                         VARCHAR(128)             NOT NULL,
    description                  VARCHAR(512),
    default_top_k                INTEGER                  NOT NULL DEFAULT 6,
    default_similarity_threshold DECIMAL(5, 4)            NOT NULL DEFAULT 0.5500,
    status                       VARCHAR(20)              NOT NULL DEFAULT 'ENABLED',
    created_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at                   TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by                   BIGINT,
    updated_by                   BIGINT,
    version                      BIGINT                   NOT NULL DEFAULT 0,
    deleted                      BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_rag_kb_code_deleted UNIQUE (code, deleted)
);

CREATE INDEX idx_rag_kb_status ON rag_knowledge_base (status);
CREATE INDEX idx_rag_kb_deleted ON rag_knowledge_base (deleted);

CREATE TABLE rag_knowledge_base_user
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    knowledge_base_id BIGINT                   NOT NULL,
    user_id           BIGINT                   NOT NULL,
    access_level      VARCHAR(20)              NOT NULL DEFAULT 'READ',
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        BIGINT,
    updated_by        BIGINT,
    version           BIGINT                   NOT NULL DEFAULT 0,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_rag_kb_user_deleted UNIQUE (knowledge_base_id, user_id, deleted),
    CONSTRAINT fk_rag_kb_user_kb FOREIGN KEY (knowledge_base_id) REFERENCES rag_knowledge_base (id),
    CONSTRAINT fk_rag_kb_user_user FOREIGN KEY (user_id) REFERENCES sys_user (id)
);

CREATE INDEX idx_rag_kb_user_user ON rag_knowledge_base_user (user_id);
CREATE INDEX idx_rag_kb_user_kb ON rag_knowledge_base_user (knowledge_base_id);

CREATE TABLE rag_file_object
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sha256            VARCHAR(64)              NOT NULL,
    storage_type      VARCHAR(20)              NOT NULL,
    bucket            VARCHAR(128),
    storage_key       VARCHAR(512)             NOT NULL,
    original_filename VARCHAR(255)             NOT NULL,
    content_type      VARCHAR(128),
    file_type         VARCHAR(20)              NOT NULL,
    file_size         BIGINT                   NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        BIGINT,
    updated_by        BIGINT,
    version           BIGINT                   NOT NULL DEFAULT 0,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_rag_file_sha_deleted UNIQUE (sha256, deleted)
);

CREATE INDEX idx_rag_file_sha ON rag_file_object (sha256);
CREATE INDEX idx_rag_file_deleted ON rag_file_object (deleted);

CREATE TABLE rag_user_document
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id             BIGINT                   NOT NULL,
    knowledge_base_id   BIGINT                   NOT NULL,
    file_object_id      BIGINT,
    display_name        VARCHAR(255)             NOT NULL,
    source_type         VARCHAR(20)              NOT NULL,
    file_type           VARCHAR(20)              NOT NULL,
    content_hash        VARCHAR(64)              NOT NULL,
    status              VARCHAR(20)              NOT NULL DEFAULT 'UPLOADED',
    chunk_count         INTEGER                  NOT NULL DEFAULT 0,
    indexed_chunk_count INTEGER                  NOT NULL DEFAULT 0,
    error_message       VARCHAR(1024),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by          BIGINT,
    updated_by          BIGINT,
    version             BIGINT                   NOT NULL DEFAULT 0,
    deleted             BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_rag_doc_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_rag_doc_kb FOREIGN KEY (knowledge_base_id) REFERENCES rag_knowledge_base (id),
    CONSTRAINT fk_rag_doc_file FOREIGN KEY (file_object_id) REFERENCES rag_file_object (id)
);

CREATE INDEX idx_rag_doc_user ON rag_user_document (user_id);
CREATE INDEX idx_rag_doc_kb_status ON rag_user_document (knowledge_base_id, status);
CREATE INDEX idx_rag_doc_hash ON rag_user_document (content_hash);
CREATE INDEX idx_rag_doc_deleted ON rag_user_document (deleted);

CREATE TABLE rag_document_chunk
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id       BIGINT                   NOT NULL,
    knowledge_base_id BIGINT                   NOT NULL,
    file_object_id    BIGINT,
    chunk_index       INTEGER                  NOT NULL,
    content           TEXT                     NOT NULL,
    content_preview   VARCHAR(512)             NOT NULL,
    token_count       INTEGER                  NOT NULL DEFAULT 0,
    enabled           BOOLEAN                  NOT NULL DEFAULT TRUE,
    vector_id         VARCHAR(64),
    metadata_json     TEXT,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        BIGINT,
    updated_by        BIGINT,
    version           BIGINT                   NOT NULL DEFAULT 0,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_rag_chunk_doc_index_deleted UNIQUE (document_id, chunk_index, deleted),
    CONSTRAINT fk_rag_chunk_doc FOREIGN KEY (document_id) REFERENCES rag_user_document (id),
    CONSTRAINT fk_rag_chunk_kb FOREIGN KEY (knowledge_base_id) REFERENCES rag_knowledge_base (id),
    CONSTRAINT fk_rag_chunk_file FOREIGN KEY (file_object_id) REFERENCES rag_file_object (id)
);

CREATE INDEX idx_rag_chunk_doc ON rag_document_chunk (document_id);
CREATE INDEX idx_rag_chunk_kb_enabled ON rag_document_chunk (knowledge_base_id, enabled);
CREATE INDEX idx_rag_chunk_deleted ON rag_document_chunk (deleted);

CREATE TABLE rag_ingestion_job
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id       BIGINT                   NOT NULL,
    knowledge_base_id BIGINT                   NOT NULL,
    file_object_id    BIGINT,
    status            VARCHAR(20)              NOT NULL DEFAULT 'PENDING',
    current_step      VARCHAR(20)              NOT NULL DEFAULT 'UPLOAD',
    progress          INTEGER                  NOT NULL DEFAULT 0,
    chunk_count       INTEGER                  NOT NULL DEFAULT 0,
    success_count     INTEGER                  NOT NULL DEFAULT 0,
    failed_count      INTEGER                  NOT NULL DEFAULT 0,
    error_message     VARCHAR(1024),
    started_at        TIMESTAMP WITH TIME ZONE,
    finished_at       TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by        BIGINT,
    updated_by        BIGINT,
    version           BIGINT                   NOT NULL DEFAULT 0,
    deleted           BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_rag_job_doc FOREIGN KEY (document_id) REFERENCES rag_user_document (id),
    CONSTRAINT fk_rag_job_kb FOREIGN KEY (knowledge_base_id) REFERENCES rag_knowledge_base (id),
    CONSTRAINT fk_rag_job_file FOREIGN KEY (file_object_id) REFERENCES rag_file_object (id)
);

CREATE INDEX idx_rag_job_doc ON rag_ingestion_job (document_id);
CREATE INDEX idx_rag_job_kb_status ON rag_ingestion_job (knowledge_base_id, status);
CREATE INDEX idx_rag_job_deleted ON rag_ingestion_job (deleted);
