CREATE TABLE agent_memory_space
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id      VARCHAR(96)              NOT NULL,
    owner_user_id BIGINT                   NOT NULL,
    name          VARCHAR(128)             NOT NULL,
    status        VARCHAR(32)              NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    version       BIGINT                   NOT NULL DEFAULT 0,
    deleted       BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_agent_memory_space_space_id UNIQUE (space_id)
);

CREATE INDEX idx_agent_memory_space_owner_status
    ON agent_memory_space (owner_user_id, status, updated_at);

CREATE TABLE agent_external_chat_binding
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_id                 VARCHAR(96)              NOT NULL,
    platform                 VARCHAR(32)              NOT NULL,
    connector_id             VARCHAR(96)              NOT NULL,
    external_conversation_id VARCHAR(192)             NOT NULL,
    conversation_type        VARCHAR(32)              NOT NULL,
    audience_key             VARCHAR(256)             NOT NULL,
    enabled                  BOOLEAN                  NOT NULL DEFAULT TRUE,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    version                  BIGINT                   NOT NULL DEFAULT 0,
    deleted                  BOOLEAN                  NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_agent_external_binding_conversation UNIQUE
        (platform, connector_id, external_conversation_id)
);

CREATE INDEX idx_agent_external_binding_space
    ON agent_external_chat_binding (space_id, enabled, deleted);

CREATE TABLE agent_external_chat_event
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform                 VARCHAR(32)              NOT NULL,
    connector_id             VARCHAR(96)              NOT NULL,
    external_event_id        VARCHAR(192)             NOT NULL,
    external_message_id      VARCHAR(192),
    space_id                 VARCHAR(96),
    owner_user_id            BIGINT,
    normalized_message_json  TEXT                     NOT NULL,
    processing_status        VARCHAR(32)              NOT NULL,
    guard_decision           VARCHAR(32),
    reply_status             VARCHAR(32)              NOT NULL,
    assistant_message_id     BIGINT,
    reply_version            INTEGER                  NOT NULL DEFAULT 1,
    attempts                 INTEGER                  NOT NULL DEFAULT 0,
    available_at             TIMESTAMP WITH TIME ZONE NOT NULL,
    locked_at                TIMESTAMP WITH TIME ZONE,
    locked_by                VARCHAR(128),
    request_id               VARCHAR(64),
    trace_id                 VARCHAR(64),
    received_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    processed_at             TIMESTAMP WITH TIME ZONE,
    error_code               VARCHAR(128),
    error_message            TEXT,
    metadata_json            TEXT,
    created_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at               TIMESTAMP WITH TIME ZONE NOT NULL,
    version                  BIGINT                   NOT NULL DEFAULT 0,
    CONSTRAINT uk_agent_external_event_source UNIQUE
        (platform, connector_id, external_event_id)
);

CREATE INDEX idx_agent_external_event_poll
    ON agent_external_chat_event (processing_status, available_at, received_at, id);
CREATE INDEX idx_agent_external_event_space_order
    ON agent_external_chat_event (space_id, received_at, id);

CREATE TABLE agent_chat_guard_audit
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_user_id        BIGINT,
    chat_source          VARCHAR(32)              NOT NULL,
    memory_space_id      VARCHAR(96),
    platform             VARCHAR(32),
    connector_id         VARCHAR(96),
    conversation_id      VARCHAR(192),
    conversation_type    VARCHAR(32),
    audience_key         VARCHAR(256),
    decision             VARCHAR(32)              NOT NULL,
    confidence           DECIMAL(6, 5),
    reason               VARCHAR(1000)            NOT NULL,
    model_provider       VARCHAR(32),
    model_name           VARCHAR(128),
    duration_ms          BIGINT                   NOT NULL,
    request_id           VARCHAR(64)              NOT NULL,
    trace_id             VARCHAR(64),
    external_event_id    VARCHAR(192),
    created_at           TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_agent_chat_guard_audit_request
    ON agent_chat_guard_audit (request_id, created_at);
CREATE INDEX idx_agent_chat_guard_audit_space
    ON agent_chat_guard_audit (memory_space_id, created_at);

ALTER TABLE agent_memory_session ADD COLUMN memory_domain VARCHAR(32) NOT NULL DEFAULT 'WEB_PRIVATE';
ALTER TABLE agent_memory_session ADD COLUMN memory_space_id VARCHAR(96);
CREATE INDEX idx_agent_memory_session_domain_space
    ON agent_memory_session (memory_domain, memory_space_id, updated_at);

ALTER TABLE agent_memory_message ADD COLUMN memory_domain VARCHAR(32) NOT NULL DEFAULT 'WEB_PRIVATE';
ALTER TABLE agent_memory_message ADD COLUMN memory_space_id VARCHAR(96);
ALTER TABLE agent_memory_message ADD COLUMN source_platform VARCHAR(32);
ALTER TABLE agent_memory_message ADD COLUMN source_connector_id VARCHAR(96);
ALTER TABLE agent_memory_message ADD COLUMN source_conversation_id VARCHAR(192);
ALTER TABLE agent_memory_message ADD COLUMN source_conversation_type VARCHAR(32);
ALTER TABLE agent_memory_message ADD COLUMN audience_key VARCHAR(256);
ALTER TABLE agent_memory_message ADD COLUMN external_event_id VARCHAR(192);
ALTER TABLE agent_memory_message ADD COLUMN external_message_id VARCHAR(192);
ALTER TABLE agent_memory_message ADD COLUMN external_sender_id VARCHAR(192);
ALTER TABLE agent_memory_message ADD COLUMN external_sender_display_name VARCHAR(256);
ALTER TABLE agent_memory_message ADD COLUMN observed_only BOOLEAN NOT NULL DEFAULT FALSE;
CREATE INDEX idx_agent_memory_message_space_id
    ON agent_memory_message (memory_space_id, id);
CREATE INDEX idx_agent_memory_message_external_event
    ON agent_memory_message (source_platform, source_connector_id, external_event_id);

ALTER TABLE agent_long_term_memory ADD COLUMN memory_space_id VARCHAR(96);
ALTER TABLE agent_long_term_memory ADD COLUMN scope_key VARCHAR(128) NOT NULL DEFAULT '__web_private__';
DROP INDEX idx_agent_long_term_memory_user_scope;
CREATE UNIQUE INDEX idx_agent_long_term_memory_owner_scope_key
    ON agent_long_term_memory (user_id, scope_type, scope_key);

ALTER TABLE agent_memory_extraction_audit ADD COLUMN memory_space_id VARCHAR(96);
