ALTER TABLE sys_user
    ADD COLUMN activated_at TIMESTAMP WITH TIME ZONE;

UPDATE sys_user
SET activated_at = created_at
WHERE activated_at IS NULL;

CREATE TABLE sys_one_time_token
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL,
    purpose    VARCHAR(32)              NOT NULL,
    token_hash VARCHAR(64)              NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_by BIGINT,
    CONSTRAINT uk_one_time_token_hash UNIQUE (token_hash),
    CONSTRAINT uk_one_time_token_user_purpose UNIQUE (user_id, purpose),
    CONSTRAINT fk_one_time_token_user FOREIGN KEY (user_id) REFERENCES sys_user (id)
);

CREATE INDEX idx_one_time_token_expires ON sys_one_time_token (expires_at);
