CREATE TABLE ai_model_call_audit
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id         VARCHAR(64),
    trace_id           VARCHAR(64),
    user_id            BIGINT,
    session_id         VARCHAR(128),
    thread_id          VARCHAR(128),
    scenario           VARCHAR(32)              NOT NULL,
    provider           VARCHAR(32)              NOT NULL,
    model              VARCHAR(128)             NOT NULL,
    options_json       TEXT,
    prompt_tokens      INTEGER,
    completion_tokens  INTEGER,
    total_tokens       INTEGER,
    token_usage_source VARCHAR(32)              NOT NULL,
    streaming          BOOLEAN                  NOT NULL DEFAULT FALSE,
    status             VARCHAR(32)              NOT NULL,
    started_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    duration_ms        BIGINT,
    error_code         VARCHAR(256),
    error_message      VARCHAR(1024),
    prompt_chars       INTEGER,
    completion_chars   INTEGER,
    ip                 VARCHAR(64),
    user_agent         VARCHAR(512),
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_ai_model_audit_user_created ON ai_model_call_audit (user_id, created_at);
CREATE INDEX idx_ai_model_audit_trace ON ai_model_call_audit (trace_id);
CREATE INDEX idx_ai_model_audit_provider_model ON ai_model_call_audit (provider, model);
CREATE INDEX idx_ai_model_audit_status ON ai_model_call_audit (status);
