package top.egon.mario.rbac.converter;

import io.github.linpeilie.Converter;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import top.egon.mario.rbac.dto.response.PermissionResponse;
import top.egon.mario.rbac.po.ApiPo;
import top.egon.mario.rbac.po.ButtonPo;
import top.egon.mario.rbac.po.MenuPo;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Verifies RBAC DTO mappings generated by MapStruct Plus.
 */
@SpringBootTest(properties = "spring.ai.dashscope.api-key=test-api-key")
class RbacDtoConverterTests {

    @Autowired
    private Converter converter;

    @Test
    void mapStructPlusConvertsMenuDetail() {
        MenuPo menuPo = new MenuPo();
        menuPo.setParentMenuId(10L);
        menuPo.setRouteName("rbac-user");
        menuPo.setRoutePath("/rbac/users");
        menuPo.setComponent("rbac/user/index");
        menuPo.setRedirect("/rbac/users/list");
        menuPo.setIcon("users");
        menuPo.setHidden(true);
        menuPo.setCacheable(false);
        menuPo.setExternalLink("https://example.test/rbac/users");

        PermissionResponse.MenuDetail detail = converter.convert(menuPo, PermissionResponse.MenuDetail.class);

        assertThat(detail.getParentMenuId()).isEqualTo(10L);
        assertThat(detail.getRouteName()).isEqualTo("rbac-user");
        assertThat(detail.getRoutePath()).isEqualTo("/rbac/users");
        assertThat(detail.getComponent()).isEqualTo("rbac/user/index");
        assertThat(detail.getRedirect()).isEqualTo("/rbac/users/list");
        assertThat(detail.getIcon()).isEqualTo("users");
        assertThat(detail.isHidden()).isTrue();
        assertThat(detail.isCacheable()).isFalse();
        assertThat(detail.getExternalLink()).isEqualTo("https://example.test/rbac/users");
    }

    @Test
    void mapStructPlusConvertsButtonDetail() {
        ButtonPo buttonPo = new ButtonPo();
        buttonPo.setMenuPermissionId(20L);
        buttonPo.setButtonKey("create");
        buttonPo.setFrontendAction("rbac:user:create");
        buttonPo.setStyleHint("primary");
        buttonPo.setDescription("create user");

        PermissionResponse.ButtonDetail detail = converter.convert(buttonPo, PermissionResponse.ButtonDetail.class);

        assertThat(detail.getMenuPermissionId()).isEqualTo(20L);
        assertThat(detail.getButtonKey()).isEqualTo("create");
        assertThat(detail.getFrontendAction()).isEqualTo("rbac:user:create");
        assertThat(detail.getStyleHint()).isEqualTo("primary");
        assertThat(detail.getDescription()).isEqualTo("create user");
    }

    @Test
    void mapStructPlusConvertsApiDetail() {
        ApiPo apiPo = new ApiPo();
        apiPo.setHttpMethod("GET");
        apiPo.setUrlPattern("/api/rbac/users");
        apiPo.setMatcherType(top.egon.mario.rbac.po.enums.ApiMatcherType.MVC);
        apiPo.setPublicFlag(true);
        apiPo.setServiceTag("rbac");
        apiPo.setOperationName("list users");
        apiPo.setRiskLevel(top.egon.mario.rbac.po.enums.ApiRiskLevel.MEDIUM);

        PermissionResponse.ApiDetail detail = converter.convert(apiPo, PermissionResponse.ApiDetail.class);

        assertThat(detail.getHttpMethod()).isEqualTo("GET");
        assertThat(detail.getUrlPattern()).isEqualTo("/api/rbac/users");
        assertThat(detail.getMatcherType()).isEqualTo(top.egon.mario.rbac.dto.enums.ApiMatcherType.MVC);
        assertThat(detail.isPublicFlag()).isTrue();
        assertThat(detail.getServiceTag()).isEqualTo("rbac");
        assertThat(detail.getOperationName()).isEqualTo("list users");
        assertThat(detail.getRiskLevel()).isEqualTo(top.egon.mario.rbac.dto.enums.ApiRiskLevel.MEDIUM);
    }

}
