package top.egon.mario.clocktower.common.enums;

public enum ClocktowerEventType {
    ROOM_CREATED,
    PLAYER_JOINED,
    PLAYER_LEFT,
    SEAT_UPDATED,
    ROLE_ASSIGNED,
    PHASE_CHANGED,
    PUBLIC_MESSAGE_SENT,
    PRIVATE_MESSAGE_SENT,
    NIGHT_STEP_UPDATED,
    NIGHT_ACTION_SUBMITTED,
    PLAYER_NOMINATED,
    VOTE_CAST,
    DEAD_VOTE_SPENT,
    PLAYER_EXECUTED,
    EXECUTION_SKIPPED,
    PLAYER_DIED,
    PLAYER_PASSED,
    MARKER_ADDED,
    MARKER_REMOVED,
    STORYTELLER_RULING,
    GAME_ENDED,
    ACTION_REJECTED
}
