import type {
    NutritionAiRecommendationJobResponse,
    NutritionAiRecommendationResponse,
    NutritionBudgetSummaryResponse,
    NutritionClanResponse,
    NutritionFamilyResponse,
    NutritionHealthProfileResponse,
    NutritionImportJobResponse,
    NutritionMealConfirmationResponse,
    NutritionMealPlanResponse,
    NutritionMealPlanSummaryResponse,
    NutritionMemberProfileResponse,
    NutritionRecipeResponse,
    NutritionShoppingListResponse,
    NutritionStandardFoodResponse,
} from './nutritionTypes'

const now = '2026-07-01T00:00:00Z'

export const nutritionFamilies: NutritionFamilyResponse[] = [
    {
        id: 1,
        name: '星河家庭',
        ownerUserId: 1001,
        region: '上海',
        currency: 'CNY',
        defaultMealTypes: ['BREAKFAST', 'LUNCH', 'DINNER'],
        aiEnabled: true,
        aiGenerateTime: '17:30',
        healthAlertEnabled: true,
        budgetEnabled: true,
        status: 'ACTIVE',
        ownerMemberProfileId: 11,
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 2,
        name: '周末照护家庭',
        ownerUserId: 1002,
        region: '杭州',
        currency: 'CNY',
        defaultMealTypes: ['LUNCH', 'DINNER'],
        aiEnabled: false,
        aiGenerateTime: null,
        healthAlertEnabled: true,
        budgetEnabled: true,
        status: 'ACTIVE',
        ownerMemberProfileId: 21,
        createdAt: now,
        updatedAt: now,
    },
]

export const nutritionClans: NutritionClanResponse[] = [
    {id: 1, name: '三代同堂', ownerUserId: 1001, status: 'ACTIVE', createdAt: now, updatedAt: now},
    {id: 2, name: '托管亲友圈', ownerUserId: 1002, status: 'ACTIVE', createdAt: now, updatedAt: now},
]

export const nutritionMembers: NutritionMemberProfileResponse[] = [
    {
        id: 11,
        familyId: 1,
        boundUserId: 1001,
        nickname: 'Mario',
        gender: 'MALE',
        birthDate: '1989-03-12',
        heightCm: 176,
        weightKg: 72,
        memberType: 'ADULT',
        loginEnabled: true,
        guardianMemberId: null,
        status: 'ACTIVE',
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 12,
        familyId: 1,
        boundUserId: null,
        nickname: '小米',
        gender: 'FEMALE',
        birthDate: '2016-05-18',
        heightCm: 132,
        weightKg: 28,
        memberType: 'CHILD',
        loginEnabled: false,
        guardianMemberId: 11,
        status: 'ACTIVE',
        createdAt: now,
        updatedAt: now,
    },
]

export const nutritionHealthProfiles: NutritionHealthProfileResponse[] = [
    {
        id: 101,
        familyId: 1,
        memberProfileId: 11,
        activityLevel: '中等活动',
        dietGoals: ['控钠', '增肌'],
        allergyTags: [],
        dislikeTags: ['香菜'],
        restrictionTags: [],
        targetCalories: 2100,
        targetProtein: 110,
        targetFat: 65,
        targetCarbs: 260,
        targetSodium: 2000,
        targetSugar: 40,
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 102,
        familyId: 1,
        memberProfileId: 12,
        activityLevel: '儿童日常',
        dietGoals: ['均衡成长'],
        allergyTags: ['花生'],
        dislikeTags: [],
        restrictionTags: ['低糖'],
        targetCalories: 1600,
        targetProtein: 55,
        targetFat: 45,
        targetCarbs: 210,
        targetSodium: 1500,
        targetSugar: 25,
        createdAt: now,
        updatedAt: now,
    },
]

export const standardFoods: NutritionStandardFoodResponse[] = [
    {
        id: 1,
        nameCn: '鸡胸肉',
        nameEn: 'Chicken breast',
        category: '肉禽蛋',
        caloriesPer100g: 165,
        proteinPer100g: 31,
        fatPer100g: 3.6,
        carbsPer100g: 0,
        dataQuality: 'FIXTURE',
        status: 'ACTIVE',
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 2,
        nameCn: '西兰花',
        nameEn: 'Broccoli',
        category: '蔬菜',
        caloriesPer100g: 34,
        proteinPer100g: 2.8,
        fatPer100g: 0.4,
        carbsPer100g: 6.6,
        dataQuality: 'FIXTURE',
        status: 'ACTIVE',
        createdAt: now,
        updatedAt: now,
    },
]

export const familyRecipes: NutritionRecipeResponse[] = [
    {
        id: 201,
        familyId: 1,
        sourceType: 'FAMILY_PRIVATE',
        name: '番茄鸡胸饭',
        category: '工作日晚餐',
        description: '高蛋白低油版本',
        servingCount: 3,
        suitableTags: [],
        allergenTags: [],
        status: 'ACTIVE',
        ingredients: [
            {id: 1, recipeId: 201, standardFoodId: 1, rawFoodName: '鸡胸肉', amount: 350, unit: 'g', mappingStatus: 'MAPPED', optional: false},
            {id: 2, recipeId: 201, standardFoodId: null, rawFoodName: '本地番茄', amount: 4, unit: '个', mappingStatus: 'PENDING', optional: false},
        ],
        steps: [],
        createdAt: now,
        updatedAt: now,
    },
    {
        id: 202,
        familyId: 1,
        sourceType: 'PLATFORM_PUBLIC',
        name: '西兰花炒蛋',
        category: '公共菜谱',
        description: '儿童友好',
        servingCount: 2,
        suitableTags: [],
        allergenTags: [],
        status: 'ACTIVE',
        ingredients: [
            {id: 3, recipeId: 202, standardFoodId: 2, rawFoodName: '西兰花', amount: 240, unit: 'g', mappingStatus: 'MAPPED', optional: false},
        ],
        steps: [],
        createdAt: now,
        updatedAt: now,
    },
]

export const aiJobs: NutritionAiRecommendationJobResponse[] = [
    {
        id: 301,
        familyId: 1,
        triggerType: 'SCHEDULED',
        status: 'SUCCEEDED',
        requestedBy: 1001,
        plannedDate: '2026-07-02',
        targetMealTypes: ['DINNER'],
        recommendationId: 401,
        mealPlanId: 501,
        errorMessage: null,
        startedAt: now,
        completedAt: now,
        createdAt: now,
        updatedAt: now,
    },
]

export const aiRecommendations: NutritionAiRecommendationResponse[] = [
    {
        id: 401,
        familyId: 1,
        aiJobId: 301,
        recommendationDate: '2026-07-02',
        title: '三人晚餐建议',
        reason: '控制钠摄入并照顾儿童花生过敏',
        mealTypes: ['DINNER'],
        costEstimate: 86.5,
        status: 'ACTIVE',
        mealPlanId: 501,
        createdAt: now,
        updatedAt: now,
    },
]

export const mealPlans: NutritionMealPlanResponse[] = [
    {
        id: 501,
        familyId: 1,
        aiRecommendationId: 401,
        planDate: '2026-07-02',
        status: 'PENDING_REVIEW',
        title: '周四家庭晚餐',
        publishedAt: null,
        confirmationCutoffAt: '2026-07-02T15:00:00Z',
        confirmedMemberCount: 1,
        estimatedCost: 86.5,
        items: [
            {id: 1, mealPlanId: 501, mealType: 'DINNER', recipeId: 201, dishName: '番茄鸡胸饭', servingCount: 3, sortOrder: 1},
            {id: 2, mealPlanId: 501, mealType: 'DINNER', recipeId: 202, dishName: '西兰花炒蛋', servingCount: 2, sortOrder: 2},
        ],
        createdAt: now,
        updatedAt: now,
    },
]

export const mealConfirmations: NutritionMealConfirmationResponse[] = [
    {
        id: 601,
        familyId: 1,
        mealPlanId: 501,
        memberProfileId: 11,
        eatAtHome: true,
        selectedMealTypes: ['DINNER'],
        riskConfirmed: true,
        riskConfirmationNote: '已确认控钠',
        remark: '少盐',
        confirmedByUserId: 1001,
        proxyByUserId: null,
        confirmationStatus: 'CONFIRMED',
        confirmedAt: now,
        createdAt: now,
        updatedAt: now,
    },
]

export const mealSummary: NutritionMealPlanSummaryResponse = {
    mealPlanId: 501,
    confirmedMemberCount: 2,
    dishes: [
        {itemId: 1, dishName: '番茄鸡胸饭', mealType: 'DINNER', servingCount: 3, confirmedServingTotal: 2.5},
        {itemId: 2, dishName: '西兰花炒蛋', mealType: 'DINNER', servingCount: 2, confirmedServingTotal: 2},
    ],
}

export const shoppingList: NutritionShoppingListResponse = {
    id: 701,
    familyId: 1,
    mealPlanId: 501,
    listDate: '2026-07-02',
    status: 'ACTIVE',
    title: '周四晚餐采购',
    estimatedTotalPrice: 86.5,
    actualTotalPrice: 79.8,
    items: [
        {
            id: 1,
            shoppingListId: 701,
            standardFoodId: 1,
            rawFoodName: '鸡胸肉',
            category: '肉禽蛋',
            plannedAmount: 350,
            plannedUnit: 'g',
            purchasedAmount: 500,
            purchasedUnit: 'g',
            channel: '盒马',
            brand: '日日鲜',
            specAmount: 500,
            specUnit: 'g',
            purchaseQuantity: 1,
            totalPrice: 24.9,
            normalizedUnitPrice: 49.8,
            itemStatus: 'CHECKED',
            note: '已勾选',
            createdAt: now,
            updatedAt: now,
        },
        {
            id: 2,
            shoppingListId: 701,
            standardFoodId: 2,
            rawFoodName: '西兰花',
            category: '蔬菜',
            plannedAmount: 240,
            plannedUnit: 'g',
            purchasedAmount: null,
            purchasedUnit: null,
            channel: null,
            brand: null,
            specAmount: null,
            specUnit: null,
            purchaseQuantity: null,
            totalPrice: null,
            normalizedUnitPrice: null,
            itemStatus: 'OPEN',
            note: null,
            createdAt: now,
            updatedAt: now,
        },
    ],
    createdAt: now,
    updatedAt: now,
}

export const weeklyBudget: NutritionBudgetSummaryResponse = {
    periodType: 'WEEK',
    periodStart: '2026-06-29',
    periodEnd: '2026-07-05',
    totalAmount: 620,
    totalActualAmount: 308,
    totalEstimatedAmount: 540,
    mealPlanCount: 6,
    mealCount: 14,
    confirmedMemberCount: 24,
    perPersonCost: 12.83,
    usageRate: 49.7,
    dailySummaries: [{date: '2026-07-01', actual: 79.8, estimated: 86.5}],
    dishSummaries: [{dishName: '番茄鸡胸饭', actual: 32.5}],
    ingredientSummaries: [{name: '鸡胸肉', actual: 24.9}],
    channelSummaries: [{channel: '盒马', actual: 79.8}],
}

export const monthlyBudget: NutritionBudgetSummaryResponse = {
    ...weeklyBudget,
    periodType: 'MONTH',
    periodStart: '2026-07-01',
    periodEnd: '2026-07-31',
    totalAmount: 2600,
    totalActualAmount: 308,
    totalEstimatedAmount: 2320,
    usageRate: 11.8,
}

export const platformImportJob: NutritionImportJobResponse = {
    id: 801,
    familyId: null,
    importType: 'STANDARD_FOOD',
    fileName: 'standard-foods.csv',
    status: 'PREVIEW_READY',
    totalRows: 120,
    successRows: 118,
    failedRows: 0,
    warningRows: 2,
    errorSummary: null,
    errors: [],
    createdAt: now,
    completedAt: null,
    confirmedAt: null,
}
