import type {
    NutritionFamilyResponse,
    NutritionHealthProfileResponse,
    NutritionHealthTagResponse,
    NutritionHomeOverviewResponse,
    NutritionMemberProfileResponse,
    NutritionRecipeResponse,
    NutritionStandardFoodResponse,
} from '../nutritionTypes'

export const family: NutritionFamilyResponse = {
    id: 7,
    name: 'Mario Family',
    ownerUserId: 1,
    region: 'Shanghai',
    currency: 'CNY',
    defaultMealTypes: ['DINNER'],
    aiEnabled: false,
    aiGenerateTime: '07:30:00',
    healthAlertEnabled: true,
    budgetEnabled: true,
    status: 'ACTIVE',
    ownerMemberProfileId: 11,
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
}

export const member: NutritionMemberProfileResponse = {
    id: 11,
    familyId: family.id,
    boundUserId: 1,
    nickname: 'Mario',
    memberType: 'ADULT',
    loginEnabled: true,
    status: 'ACTIVE',
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
}

export const healthProfile: NutritionHealthProfileResponse = {
    id: 21,
    familyId: family.id,
    memberProfileId: member.id,
    activityLevel: 'MODERATE',
    dietGoals: ['LOW_SUGAR'],
    allergyTags: ['PEANUT'],
    dislikeTags: [],
    restrictionTags: [],
    targetCalories: '2000',
    targetProtein: '100',
    targetFat: '60',
    targetCarbs: '250',
    targetSodium: '2000',
    targetSugar: '50',
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
}

export const healthTag: NutritionHealthTagResponse = {
    id: 31,
    tagType: 'ALLERGY_TAG',
    tagCode: 'PEANUT',
    name: '花生',
    description: '花生过敏',
    sortOrder: 1,
    status: 'ACTIVE',
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
}

export const standardFood: NutritionStandardFoodResponse = {
    id: 41,
    nameCn: '鸡胸肉',
    nameEn: 'Chicken breast',
    aliases: [],
    category: 'MEAT',
    caloriesPer100g: '165',
    proteinPer100g: '31',
    fatPer100g: '3.6',
    carbsPer100g: '0',
    sugarPer100g: '0',
    sodiumPer100g: '74',
    fiberPer100g: '0',
    cholesterolPer100g: '85',
    allergenTags: [],
    suitableTags: [],
    dataQuality: 'CURATED',
    status: 'ACTIVE',
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
}

export const recipe: NutritionRecipeResponse = {
    id: 51,
    familyId: family.id,
    sourceType: 'FAMILY_PRIVATE',
    name: '鸡胸肉沙拉',
    category: 'DINNER',
    description: '简单晚餐',
    servingCount: 2,
    cookingMinutes: 20,
    difficultyLevel: 'EASY',
    suitableTags: [],
    allergenTags: [],
    status: 'ACTIVE',
    ingredients: [{
        id: 61,
        recipeId: 51,
        rawFoodName: '鸡胸肉',
        amount: '200',
        unit: 'g',
        mappingStatus: 'UNMAPPED',
        optional: false,
    }],
    steps: [{id: 71, recipeId: 51, stepNo: 1, title: '准备', instruction: '切块'}],
    createdAt: '2026-07-01T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
}

export const homeOverview: NutritionHomeOverviewResponse = {
    familyId: family.id,
    date: '2026-07-13',
    mealPlans: [{
        id: 81,
        familyId: family.id,
        planDate: '2026-07-13',
        status: 'CONFIRMING',
        version: 1,
        title: 'Sunday dinner',
        confirmedMemberCount: 1,
        estimatedCost: '50',
        risks: [],
        publishable: true,
        items: [],
        createdAt: '2026-07-01T00:00:00Z',
        updatedAt: '2026-07-01T00:00:00Z',
    }],
    confirmedMemberCount: 1,
    awayMemberCount: 0,
    unconfirmedMemberCount: 2,
    riskCounts: {MEDIUM: 1},
    shoppingState: 'ACTIVE',
    actualCost: '42',
    estimatedCost: '50',
    budgetUsageRate: '70',
    nutritionRecordReady: false,
}
